### ISSUE TITLE
Restart the server cannot start after 1.10.2

### ISSUE THREAD

**Issue by Xiaoyan366** [DoubleDoorDevelopment/MineTweakerRecipeMaker#20]
I deleted the recipe for several items
Restart the server cannot start after
Because The current 1.10.2 build only supports crafting?

[crash-2017-01-08_17.01.32-server.txt](https://github.com/DoubleDoorDevelopment/MineTweakerRecipeMaker/files/692007/crash-2017-01-08_17.01.32-server.txt)

**Comment by dries007** [comment]
Has nothing to do with MTRM. MTRM isn't even in your modlist.

**Comment by Xiaoyan366** [comment]
[crash-2017-01-08_20.02.58-server.txt](https://github.com/DoubleDoorDevelopment/MineTweakerRecipeMaker/files/694161/crash-2017-01-08_20.02.58-server.txt)

**Comment by Xiaoyan366** [comment]
I reinstall the MTRM
The server will not start
Above is the error file already has MTRM

**Comment by Claycorp** [comment]
Just because you add MTRM after it started crashing doesn't make it our issue.

If you read the logs both clearly say that the server watchdog is what's killing the server. Turn it off and it should be fine. Also next time I advise that you don't add a mod then report that it's broken to a dev when they say it has nothing to do with them.

**Comment by dries007** [comment]
Also, it seems the actual source of the crash is whatever this mod is:

	at net.wwsf.domochevsky.tinb.Main.loadFromFile(Main.java:407)
	at net.wwsf.domochevsky.tinb.Main.serverLoad(Main.java:88)
