### ISSUE TITLE
1.10.2 Crash with Terraqueous Scrolls

### ISSUE THREAD

**Issue by MokahTGS** [DoubleDoorDevelopment/MineTweakerRecipeMaker#23]
Getting a crash trying to make a recipe for the Ancient Scroll item from Terraqueous mod:

http://pastebin.com/5C3wvWCh

**Comment by dries007** [comment]
I'm pretty sure that mod is doing something its not supposed to, but I'll try and see if I can fix it.

**Comment by dries007** [comment]
The fault is with [NoMoreRecipeConflict](https://github.com/GotoLink/RecipeHandler) I believe.
That mod is kind off a mess TBH, but I believe this is what's happening:
- MTRM tells MT to reload the recipes when you change something.
- NoMoreRecipeConflict/RecipeHandler loops over the entire recipe list on rendering events.

And you can't do both of those at the same time. Since MTRM is doing nothing wrong, and NoMoreRecipeConflict/RecipeHandler is, I'm going to close this.

(The solution I think would be for the mod to use caching and not re-calculate the entire thing every single time the button renders, but only once per client tick. This happens in the same thread as the recipe handler stuff, I think, so it can't happen at the same time.)
