### ISSUE TITLE
Adding a recipe for BoP Spring Water results in just empty buckets?

### ISSUE THREAD

**Issue by katubug** [DoubleDoorDevelopment/MineTweakerRecipeMaker#44]
Hi! I've been trying to allow buckets of spring water to be craftable, but while I input the recipe correctly (I think!), the output is always just an empty bucket.

Any idea how I could fix this? Or is it a limitation of the software? Thanks in advance!

The recipe I've been using is 1 golden apple, 1 bucket of water, and 1 torch. A friend suggested it might have something to do with the byproduct of buckets?

**Comment by dries007** [comment]
Try looking at the line MTRM generated for the recipe you added and see if it it's correct, if not, it may be a limitation of MTRM.

I'm guessing it doesn't properly turn the bucket into a filled bucket because it's missing the NBT tag of the bucket, I've never tried this.

**Comment by katubug** [comment]
Pardon my noobness, but how can I check that line? Is it in my configs? I don't see a file called mtrm.

**Comment by dries007** [comment]
MTRM makes a Minetweaker script, it should be in `/scripts`, but depending on the exact version, it may be in a subfolder (I don't remember the name, but it's likely `MTRM` or `minetweakerrecipemaker`).

Open that file and look for a line that looks like the right recipe, if you have no idea what it should look like, you can put use `/mtrm` to put in the recipe and look at the screen, if I recall correctly, it shows you the entire line somewhere on screen for debugging purposes.  (It's been a long time since I've properly worked on this project though, so It's possible that was only in debug builds.)

**Comment by katubug** [comment]
Thank you so much!

Yeah, this is the line in question:

> recipes.addShaped(<forge:bucketfilled>, [[<minecraft:golden_apple>], [<minecraft:water_bucket>], [<minecraft:torch>]]);

I'm assuming that means that it's a software limitation, since it seems unable to recognize WHAT the bucket is filled with? Ah well. Thank you very much for your help!

**Comment by dries007** [comment]
You can edit the script file and add the correct nbt tag. You get the nbt
by use the '/mt hand' command (I think) while holding the item. This should
print all the stack info to the Minecraft console. (The command might have
been renamed since then, check Mine/Craft tweaker docs)

Op 1 dec. 2017 20:48 schreef "katubug" <notifications@github.com>:

**Comment by katubug** [comment]
The command worked perfectly, I'm restarting now to see if it worked. Thanks again for all your help!

Edit: It worked! You're awesome, thank you so much for walking me through this.
