### ISSUE TITLE
recipes not saving properly

### ISSUE THREAD

**Issue by Winddbourne** [DoubleDoorDevelopment/MineTweakerRecipeMaker#53]
I'm having to manually edit the recipes a lot of the time. If I omit the top row and just put an item in the centre, and one at the bottom it may move the entire recipe up a row and I have to go in and add in the missing line [null, null, null] myself . . . plus its omitting null spots in the remaining lines and that can mess things up if I don't add them.

I'm not sure why it's doing things this way but I can tell the problem is that it's not coding the recipe in lines like this:

[item spot, item spot, item spot],
[item spot, item spot, item spot],
[item spot, item spot, item spot]

I don't know if this is happening for everyone or if it's something about my mod pack that is causing it, but I figure it is worth reporting.

**Comment by Claycorp** [comment]
When you make a recipe null values are only for gaps.
Like boots for example:
```
[<iron>, null, <iron>]  
[<iron>, null, <iron>]
```
Other recipes like crafting tables are like so:
```
[<planks>, <planks>]
[<planks>, <planks>]
```
The reason for this is because minecraft then can match a recipe to any spot in the grid vs only one. Adding all those `null` slots makes recipes that should work in a 2x2 grid not work in a 2x2 and requires a 3x3 and it must be an exact match.
Thus all the unneeded `null` are removed. This is also exactly as vanilla operates.

As for the `null` getting removed in other places shapeless recipes don't use `null` and empty slots will be ignored. Make sure you don't select shapeless when you want a shaped recipe. This is also how vanilla works.

**Comment by Winddbourne** [comment]
I think you missed the problem. It's not about what Minecraft does, it's about what the mod does.  If I'm circling a recipe around a central item using all eight slots and you involuntarily remove the null spaces in my shaped recipe when I load back in I get severe problems.

Recipes that were distinct have been merged together. Lines that are actually needed are gone.  In this case, there were no recipes that should be made on a 2X2 crafting grid.  Instead, the exact location of a block of wood on the radial dial of the crafting table determined which of eight different totem parts would be crafted . . . five regular totem parts from Ancient Warfare, and the three main Irimsol totem parts. The fourth Irimsol part could actually have an in inventory crafting option but that isn't in keeping with the other parts that have to be made on the table so . . . I'll leave them as is.

Perhaps the way you are describing things is the normal way for Minecraft. Perhaps most people would use it that way despite that not being the way the actual code example works in the CraftTweaker wiki . . . But my autistic brain expected things to go where I put them unless I specified otherwise.  

Either way, it needs to be an option . . . whether you have to check a box for full crafting of 2 part recipes or whether you have to check a box to make sure your recipe isn't compressed when it isn't supposed to be.

I'll rephrase my issue . . . it's not a bug because it's working the way you want it too. But it also isn't an intuitive way of making the recipes I needed, and indeed it appears that the feature I needed doesn't exist in the mod at all right now.  

It saved properly for you and caused ME tons of problems by not doing exactly what I told it to do. If I want it to be in a 2X2 square I'll put the recipe in one using the first four squares in the top of the crafting grid . . . or I'll check a box somewhere saying to compress my recipe.  I'm very literal, like a computer. If I tell it to put parts in the third spot of the first row, and the second spot of the second row I obviously don't want it to work in a 2X2 grid . . . 

Those grids don't have that third position. So when you have the program compress it for me it is like an Allistic human rather than a computer is listening to me and twisting what I said to some other design.  I'm not being vague. I do want my part to STAY in the third space, or the fourth space if I put the part there.

It's not a bug, it's a lack of feature, or allistic thinking causing the program to act wonky on purpose. However, you want to think about it. lol

**Comment by Claycorp** [comment]
The mod has worked as expected for everyone but you, Recipes should be compacted into their smallest form. Look at how vanilla does all of it's recipes in JSON. 3x3 grids and 2x2 grids are exactly the same recipe wise, You can't say X is only for 2x2 and there is no way of knowing if it should be 2x2 or 3x3.

Either think of a better recipe or if you insist on using recipes that aren't intuitive to the player playing or use the built in scripts GUI. Otherwise you can type it by hand. It's not a feature that will be added.
